services:
  database:
    build:
      context: ${ROOT_DIR}/docker/pgsql
      dockerfile: Dockerfile
    platform: linux/amd64
    image: literp_pgsql
    container_name: literp_pgsql
    restart: always
    networks:
      - project_network
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  migration:
    image: python:3.13-slim
    container_name: literp_migration
    depends_on:
      - database
    networks:
      - project_network
    volumes:
      - ${ROOT_DIR}:/workspace
    working_dir: /workspace/python/database/migration
    environment:
      ROOT_DIR: /workspace
      DB_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}
    command: >
      /bin/sh -lc "
      pip install --no-cache-dir -r /workspace/python/requirements.txt
      && alembic -c /workspace/python/database/migration/alembic.ini upgrade head;
      "
    restart: "no"
networks:
  project_network:
    name: ${DOCKER_NETWORK}
    external: true
